# Production environment
---
services:
  rdi-web-generator:
    build: 
      context: ../
      dockerfile: deploy/Dockerfile
    command: gunicorn rdi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../ct.sfc:/home/rdi/web/ct.sfc
      - static_volume:/home/rdi/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./env.prod

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/rdi/web/staticfiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    depends_on:
      - web-generator

  letsencrypt: 
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./env.prod.letsencrypt
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  certs:
  html:
  vhost:
  acme:
